apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: konveyor-virt-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: fbladilo
  displayName: "Konveyor Virt Operator"
  publisher: "ocp-migrate-team@redhat.com"
