---
- set_fact:
    reconciled: false

- block:
  - when: not olm_managed
    block:
    - name: "Setup virt controller RBAC"
      k8s:
        state: present
        definition: "{{ lookup('template', 'virt_controller_rbac.yml.j2' )}}"

    - name: "Create virt controller CRDs"
      k8s:
        state: present
        src: "{{ role_path }}/files/{{ item }}"
      with_items:
        - "virt_v1alpha1_plan.yaml"
        - "virt_v1alpha1_migration.yaml"

  - when: olm_managed
    block:
    - name: "Patch virt controller CR for OLM"
      k8s:
        state: "present"
        definition: "{{ lookup('template', 'virt_controller_olm_patch.yml.j2') }}"

    - name: "Clean conditions and set Reconciling state"
      operator_sdk.util.k8s_status:
        api_version: virt.konveyor.io/v1alpha1
        kind: VirtController
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        force: true
        conditions: []
        status:
          phase: Reconciling

  - name: "Deploy virt controller"
    k8s:
      state : present
      definition: "{{ lookup('template', 'virt_controller.yml.j2' )}}"

  - name: "Deploy xavier analytics"
    k8s:
      state : present
      definition: "{{ lookup('template', 'xavier_analytics.yml.j2' )}}"

  - set_fact:
      reconciled: true

  always:
  - operator_sdk.util.k8s_status:
      api_version: virt.konveyor.io/v1alpha1
      kind: VirtController
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      status:
        phase: Reconciled
    when: olm_managed and reconciled

  - operator_sdk.util.k8s_status:
      api_version: virt.konveyor.io/v1alpha1
      kind: VirtController
      name: "{{ meta.name }}"
      namespace: "{{ meta.namespace }}"
      status:
        phase: Failed
    when: olm_managed and not reconciled

  - name: Retrieve virt controller status
    k8s_facts:
      api_version: virt.konveyor.io/v1alpha1
      kind: VirtController
      namespace: "{{ virt_namespace }}"
    register: controller

  - when: olm_managed and
          controller.resources is defined and
          controller.resources[0].status.conditions is defined
    block:
    - operator_sdk.util.k8s_status:
        api_version: virt.konveyor.io/v1alpha1
        kind: VirtController
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        status:
          phase: Failed
      when: item.type == 'Critical'
      with_items: "{{ controller.resources[0].status.conditions }}"
