---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  name: "openshift-migration"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virt-operator
  namespace: "openshift-migration"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtcontrollers.virt.konveyor.io
spec:
  group: virt.konveyor.io
  names:
    kind: VirtController
    listKind: VirtControllerList
    plural: virtcontrollers
    singular: virtcontroller
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  creationTimestamp: null
  name: virt-operator
  namespace: "openshift-migration"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - virt-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - virt.konveyor.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: virt-operator
  namespace: "openshift-migration"
subjects:
- kind: ServiceAccount
  name: virt-operator
roleRef:
  kind: Role
  name: virt-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: virt-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: virt-operator
    namespace: "openshift-migration"
namespace: "openshift-migration"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: "openshift-migration"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration
      name: virt-operator
  template:
    metadata:
      labels:
        app: migration
        name: virt-operator
    spec:
      serviceAccountName: virt-operator
      containers:
        - name: virt-operator
          image: "quay.io/konveyor/virt-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: OPERATOR_NAME
              value: virt-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGISTRY
              value: quay.io
            - name: PROJECT
              value: konveyor
            - name: VIRT_CONTROLLER_REPO
              value: virt-controller
            - name: VIRT_CONTROLLER_TAG
              value: latest
            - name: VIRT_PAYLOAD_REPO
              value: virt-payload
            - name: VIRT_PAYLOAD_TAG
              value: latest
            - name: VIRT_UI_REPO
              value: virt-ui
            - name: VIRT_UI_TAG
              value: latest
            - name: MA_PROJECT
              value: mrizzi
            - name: MA_REPO
              value: xavier-analytics
            - name: MA_TAG
              value: dev
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
