---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: forklift-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: forklift-operator
  template:
    metadata:
      labels:
        name: forklift-operator
    spec:
      serviceAccountName: forklift-operator
      containers:
        - name: forklift-operator
          image: "quay.io/konveyor/forklift-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "forklift-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
